services:
  
  # database container
  # ---------------------------------------------
  database:
    build: ./database
    env_file:
      - .env/database
    volumes:
      - ./database/data:/data/db

  # api container
  # ---------------------------------------------
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - "database"